# permissions for end users to view attachdefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: attachdefinition-viewer-role
rules:
- apiGroups:
  - cni.linkerd.io
  resources:
  - attachdefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cni.linkerd.io
  resources:
  - attachdefinitions/status
  verbs:
  - get
