# permissions for end users to edit attachdefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: attachdefinition-editor-role
rules:
- apiGroups:
  - cni.linkerd.io
  resources:
  - attachdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cni.linkerd.io
  resources:
  - attachdefinitions/status
  verbs:
  - get
